import logging
from pathlib import Path
from typing import Any

from litellm import model_cost
from litellm.types.utils import ModelResponse

logger = logging.getLogger(__name__)
_PRICING_TABLE: dict[str, Any] = model_cost  # pyright: ignore[reportUnknownVariableType]


def calculate_cost(model_name: str, input_tokens: int, output_tokens: int) -> float:
    """Calculate the monetary cost of a model invocation.

    Args:
        model_name: The name of the model as defined in the pricing table.
        input_tokens: Number of input tokens sent to the model.
        output_tokens: Number of output tokens generated by the model.

    Returns:
        The total calculated cost for the given token usage.

    Raises:
        RuntimeError: If the provided model_name is not found in the pricing table.
    """
    model: dict[str, Any] | None = _PRICING_TABLE.get(model_name)

    if not model:
        logger.warning("Model %s is unknown, no pricing available.", model_name)
        return 0.0

    cost: float = (
        model["input_cost_per_token"] * input_tokens
        + model["output_cost_per_token"] * output_tokens
    )
    return cost


def get_tokens_and_cost(
    model_name: str, response: ModelResponse
) -> tuple[int, int, float]:
    """Extract token usage and calculate the cost for a model response.

    Args:
        model_name: The name of the model used for the invocation.
        response: The model response object, expected to have a `usage` attribute
            containing `prompt_tokens` and `completion_tokens`.

    Returns:
        A tuple of (input_tokens, output_tokens, cost).
    """
    if not (usage := getattr(response, "usage", None)):
        logger.warning("No usage reported.")
        return 0, 0, 0.0

    input_tokens = int(usage.get("prompt_tokens", 0))
    output_tokens = int(usage.get("completion_tokens", 0))
    cost = calculate_cost(model_name, input_tokens, output_tokens)

    return input_tokens, output_tokens, cost


def track_usage(path: Path, model: str, metadata: dict[str, str], comment: str) -> None:
    if not path.exists():
        with path.open("w") as fp:
            fp.write("model,timestamp,duration,input,output,cost,comment\n")

    with path.open("a") as fp:
        timestamp = metadata.get("timestamp")
        duration = metadata.get("duration")
        input_tokens = metadata.get("input_tokens")
        output_tokens = metadata.get("output_tokens")
        cost = metadata.get("cost")

        fp.write(
            f"{model},{timestamp},{duration},{input_tokens},{output_tokens},{cost},{comment}\n"
        )
